<?php

namespace Database\Seeders;

class CourseBChaptersSeeder
{
    public static function getChapters(): array
    {
        return [
            [
                'number' => 1,
                'title' => '環境構築とゲームエンジン導入',
                'summary' => 'Expoプロジェクトにreact-native-game-engineを導入し、ゲーム開発環境を整えます。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'ゲームエンジンとは？'],
                    ['type' => 'text', 'text' => 'コースAでは React Native の標準コンポーネントと Animated API でゲームを作りましたが、このコースでは react-native-game-engine というゲームエンジンライブラリを使います。ゲームエンジンは「ゲームループ」「エンティティ管理」「システム処理」を構造化してくれるフレームワークです。'],
                    ['type' => 'tip', 'text' => 'Laravel のフレームワーク（ルーティング、ミドルウェア、Eloquent）が Web 開発を構造化するように、ゲームエンジンはゲーム開発を構造化します。自前で setInterval を管理する必要がなくなります。'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'プロジェクトのセットアップ'],
                    ['type' => 'code', 'language' => 'bash', 'code' => "# Expo プロジェクト作成\nnpx create-expo-app SpaceInvadersECS --template blank-typescript\ncd SpaceInvadersECS\n\n# ゲームエンジンのインストール\nnpm install react-native-game-engine\n\n# ナビゲーション関連\nnpx expo install @react-navigation/native @react-navigation/native-stack react-native-screens react-native-safe-area-context\n\n# AsyncStorage（スコア保存用）\nnpx expo install @react-native-async-storage/async-storage"],
                    ['type' => 'heading', 'level' => 3, 'text' => 'GameEngine コンポーネントの基本'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { GameEngine } from 'react-native-game-engine';\nimport { View, StyleSheet } from 'react-native';\n\nexport default function GameScreen() {\n  return (\n    <GameEngine\n      style={styles.container}\n      entities={{}}   // ゲーム内のオブジェクト\n      systems={[]}    // 毎フレーム実行する処理\n    />\n  );\n}\n\nconst styles = StyleSheet.create({\n  container: { flex: 1, backgroundColor: '#000' },\n});", 'filename' => 'screens/GameScreen.tsx'],
                    ['type' => 'text', 'text' => 'GameEngine コンポーネントが「ゲームループ」を自動管理します。entities にゲーム内のオブジェクト（自機、敵、弾など）を、systems に毎フレーム実行する処理（移動、衝突判定など）を定義します。'],
                    ['type' => 'comparison', 'title' => 'ゲームループの管理方法比較', 'react' => "// コースA: 手動でゲームループ管理\nuseEffect(() => {\n  const loop = setInterval(() => {\n    updateEnemies();\n    checkCollisions();\n    updateBullets();\n  }, 16);\n  return () => clearInterval(loop);\n}, []);", 'reactNative' => "// コースB: GameEngine が自動管理\n<GameEngine\n  entities={entities}\n  systems={[\n    MoveEnemies,\n    CheckCollisions,\n    MoveBullets,\n  ]}\n/>"],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'react-native-game-engine の GameEngine コンポーネントの2つの主要なpropsは？', 'options' => ['entities と systems', 'objects と functions', 'sprites と updates', 'components と hooks'], 'correct' => 0, 'explanation' => 'entities でゲームオブジェクトを、systems で毎フレームの処理を定義します。'],
                        ['question' => 'ゲームエンジンを使う最大の利点は？', 'options' => ['ゲームループの自動管理と構造化', 'グラフィックが3Dになる', '処理速度が10倍になる', 'アプリサイズが小さくなる'], 'correct' => 0, 'explanation' => 'ゲームエンジンはゲームループの管理を自動化し、ECSパターンでコードを構造化してくれます。'],
                    ]],
                ],
            ],
            [
                'number' => 2,
                'title' => 'ゲームループの理解',
                'summary' => 'GameEngineのゲームループの仕組みとupdate/renderサイクルを理解します。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'ゲームループとは？'],
                    ['type' => 'text', 'text' => 'ゲームループは「入力処理 → 状態更新 → 描画」を毎フレーム（理想的には60fps = 約16ms間隔）繰り返すサイクルです。react-native-game-engine はこのループを自動で管理してくれます。'],
                    ['type' => 'list', 'items' => ['1. タッチ入力の取得（ユーザー操作）', '2. Systems の実行（ゲームロジック）', '3. Entities の描画（画面更新）', 'これを毎フレーム繰り返す']],
                    ['type' => 'heading', 'level' => 3, 'text' => 'System 関数の構造'],
                    ['type' => 'text', 'text' => 'System は毎フレーム呼ばれる関数です。entities（全ゲームオブジェクト）と追加情報を受け取り、更新後の entities を返します。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "// System の型定義\ntype SystemFunc = (\n  entities: Record<string, any>,  // 全エンティティ\n  args: {\n    touches: any[];              // タッチイベント\n    dispatch: (event: any) => void; // イベント送信\n    time: {\n      current: number;           // 現在時刻\n      delta: number;             // 前フレームからの経過時間(ms)\n      previous: number;          // 前フレームの時刻\n    };\n  }\n) => Record<string, any>; // 更新後のエンティティを返す\n\n// 例: 移動 System\nconst MoveSystem: SystemFunc = (entities, { time }) => {\n  const player = entities.player;\n  // delta を使って端末の性能に関わらず一定速度で移動\n  player.x += player.speed * (time.delta / 16);\n  return entities;\n};", 'filename' => 'systems/MoveSystem.ts'],
                    ['type' => 'tip', 'text' => 'time.delta はフレーム間の経過時間です。これを使って速度を調整すると、端末の性能差に関わらず一定速度でゲームが動きます。Laravel のキューの retry_after に似た概念で、時間ベースの制御を行います。'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'イベントディスパッチ'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { useState, useRef } from 'react';\nimport { GameEngine } from 'react-native-game-engine';\nimport { MoveSystem } from '../systems/MoveSystem';\n\nexport default function GameScreen() {\n  const engineRef = useRef<any>(null);\n  const [score, setScore] = useState(0);\n\n  return (\n    <GameEngine\n      ref={engineRef}\n      entities={{}}\n      systems={[MoveSystem]}\n      onEvent={(event: any) => {\n        // System から dispatch されたイベントを処理\n        switch (event.type) {\n          case 'score':\n            setScore(prev => prev + event.points);\n            break;\n          case 'game-over':\n            engineRef.current?.stop();\n            break;\n        }\n      }}\n    />\n  );\n}", 'filename' => 'screens/GameScreen.tsx'],
                    ['type' => 'text', 'text' => 'dispatch を使って System から React コンポーネントにイベントを送信できます。スコア更新やゲームオーバーなど、UI の変更が必要な場合に使います。'],
                    ['type' => 'comparison', 'title' => 'イベント処理の比較', 'react' => "// Laravel のイベント\nEvent::dispatch(new ScoreUpdated(\$score));\n\n// Listener で処理\nclass UpdateScoreBoard {\n  public function handle(ScoreUpdated \$event) {\n    // スコアボード更新\n  }\n}", 'reactNative' => "// GameEngine のイベント\n// System内で:\ndispatch({ type: 'score', points: 10 });\n\n// GameEngine の onEvent で処理\nonEvent={(event) => {\n  if (event.type === 'score') {\n    setScore(prev => prev + event.points);\n  }\n}}"],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'System 関数が受け取る time.delta の意味は？', 'options' => ['前フレームからの経過時間（ミリ秒）', '現在のフレーム番号', 'ゲーム開始からの総時間', 'FPS の値'], 'correct' => 0, 'explanation' => 'time.delta は前フレームからの経過時間（ms）で、これを使ってフレームレートに依存しない移動速度を実現できます。'],
                        ['question' => 'System から React コンポーネントにイベントを送る方法は？', 'options' => ['dispatch 関数を使う', 'setState を直接呼ぶ', 'イベントリスナーを登録', 'props で渡す'], 'correct' => 0, 'explanation' => 'System 内で dispatch({ type: "event-name" }) を呼び、GameEngine の onEvent で受け取ります。'],
                    ]],
                ],
            ],
            [
                'number' => 3,
                'title' => 'Entity-Component-System',
                'summary' => 'ECSパターンの概念を理解し、エンティティとシステムの設計方法を学びます。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'ECS パターンとは？'],
                    ['type' => 'text', 'text' => 'Entity-Component-System (ECS) はゲーム開発で広く使われる設計パターンです。Laravel の MVC パターンがデータ(Model)・表示(View)・ロジック(Controller)を分離するように、ECS はゲームオブジェクト(Entity)・データ(Component)・処理(System)を分離します。'],
                    ['type' => 'list', 'items' => ['Entity（エンティティ）: ゲーム内のオブジェクト。自機、敵、弾など。ID で識別', 'Component（コンポーネント）: エンティティが持つデータ。位置、速度、HP など', 'System（システム）: エンティティのデータを処理するロジック。移動、衝突判定など']],
                    ['type' => 'comparison', 'title' => 'MVC と ECS の対応', 'react' => "// Laravel MVC\nModel → データの定義と保存\nView → 表示(Blade/React)\nController → リクエスト処理\n\n// 例: User モデル\nclass User extends Model {\n  protected \$fillable = [\n    'name', 'email', 'hp'\n  ];\n}", 'reactNative' => "// Game ECS\nEntity → ゲームオブジェクト\nComponent → データ（位置、HP等）\nSystem → ロジック（移動、判定等）\n\n// 例: Player エンティティ\nconst player = {\n  position: { x: 200, y: 500 },\n  size: { width: 40, height: 40 },\n  renderer: <PlayerSprite />,\n};"],
                    ['type' => 'heading', 'level' => 3, 'text' => 'エンティティの定義'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { View, StyleSheet, Dimensions } from 'react-native';\n\nconst { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');\n\n// レンダラーコンポーネント（エンティティの見た目）\nfunction PlayerRenderer({ position, size }: any) {\n  return (\n    <View\n      style={[\n        styles.player,\n        {\n          left: position.x,\n          top: position.y,\n          width: size.width,\n          height: size.height,\n        },\n      ]}\n    />\n  );\n}\n\nfunction EnemyRenderer({ position, size, type }: any) {\n  const colors = ['#ff0000', '#ff6600', '#ffff00'];\n  return (\n    <View\n      style={[\n        styles.enemy,\n        {\n          left: position.x,\n          top: position.y,\n          width: size.width,\n          height: size.height,\n          backgroundColor: colors[type] || '#ff0000',\n        },\n      ]}\n    />\n  );\n}\n\nconst styles = StyleSheet.create({\n  player: {\n    position: 'absolute',\n    backgroundColor: '#0f0',\n    borderTopLeftRadius: 20,\n    borderTopRightRadius: 20,\n  },\n  enemy: {\n    position: 'absolute',\n    borderRadius: 4,\n  },\n});", 'filename' => 'renderers/index.tsx'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'エンティティの登録'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "// エンティティの初期化関数\nfunction createEntities() {\n  return {\n    player: {\n      position: { x: SCREEN_WIDTH / 2 - 20, y: SCREEN_HEIGHT - 120 },\n      size: { width: 40, height: 40 },\n      renderer: <PlayerRenderer />,\n    },\n    enemy_0_0: {\n      position: { x: 50, y: 80 },\n      size: { width: 30, height: 30 },\n      type: 0,\n      alive: true,\n      renderer: <EnemyRenderer />,\n    },\n    // ... 他の敵エンティティ\n  };\n}\n\n// GameEngine に渡す\n<GameEngine\n  entities={createEntities()}\n  systems={[MoveSystem, CollisionSystem]}\n/>", 'filename' => 'screens/GameScreen.tsx'],
                    ['type' => 'text', 'text' => '各エンティティは renderer プロパティを持ち、GameEngine が自動的にそのコンポーネントを描画します。エンティティの他のプロパティ（position, size など）は props としてレンダラーに渡されます。'],
                    ['type' => 'tip', 'text' => 'Laravel の Eloquent モデルで $fillable や $casts を定義するように、エンティティでも position, size, speed などのデータ構造を明確に定義します。TypeScript の型を使えばさらに安全です。'],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'ECS パターンの3つの要素は？', 'options' => ['Entity, Component, System', 'Element, Class, Service', 'Event, Controller, State', 'Engine, Cache, Store'], 'correct' => 0, 'explanation' => 'ECS = Entity（オブジェクト）、Component（データ）、System（ロジック）の3要素で構成されます。'],
                        ['question' => 'エンティティの見た目を定義するプロパティは？', 'options' => ['renderer', 'component', 'view', 'style'], 'correct' => 0, 'explanation' => 'renderer プロパティに React コンポーネントを指定すると、GameEngine が自動描画します。'],
                    ]],
                ],
            ],
            [
                'number' => 4,
                'title' => 'ホーム画面とナビゲーション',
                'summary' => 'React Navigationでホーム画面とゲーム画面の遷移を構築します。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'アプリの画面構成'],
                    ['type' => 'text', 'text' => 'コースAと同様に React Navigation でホーム画面とゲーム画面を管理します。ECS 方式でもナビゲーション部分は同じです。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { NavigationContainer } from '@react-navigation/native';\nimport { createNativeStackNavigator } from '@react-navigation/native-stack';\nimport HomeScreen from './screens/HomeScreen';\nimport GameScreen from './screens/GameScreen';\n\nexport type RootStackParamList = {\n  Home: undefined;\n  Game: undefined;\n};\n\nconst Stack = createNativeStackNavigator<RootStackParamList>();\n\nexport default function App() {\n  return (\n    <NavigationContainer>\n      <Stack.Navigator screenOptions={{ headerShown: false }}>\n        <Stack.Screen name=\"Home\" component={HomeScreen} />\n        <Stack.Screen name=\"Game\" component={GameScreen} />\n      </Stack.Navigator>\n    </NavigationContainer>\n  );\n}", 'filename' => 'App.tsx'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'ホーム画面の実装'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { useEffect, useState } from 'react';\nimport { View, Text, TouchableOpacity, StyleSheet, StatusBar } from 'react-native';\nimport AsyncStorage from '@react-native-async-storage/async-storage';\nimport type { NativeStackNavigationProp } from '@react-navigation/native-stack';\nimport type { RootStackParamList } from '../App';\n\ntype Props = {\n  navigation: NativeStackNavigationProp<RootStackParamList, 'Home'>;\n};\n\nexport default function HomeScreen({ navigation }: Props) {\n  const [highScore, setHighScore] = useState(0);\n\n  useEffect(() => {\n    const load = async () => {\n      const score = await AsyncStorage.getItem('highScore');\n      if (score) setHighScore(parseInt(score));\n    };\n    load();\n  }, []);\n\n  return (\n    <View style={styles.container}>\n      <StatusBar barStyle=\"light-content\" />\n      <Text style={styles.emoji}>👾</Text>\n      <Text style={styles.title}>SPACE INVADERS</Text>\n      <Text style={styles.subtitle}>- ECS Edition -</Text>\n      <Text style={styles.highScore}>HIGH SCORE: {highScore}</Text>\n\n      <TouchableOpacity\n        style={styles.startButton}\n        onPress={() => navigation.navigate('Game')}\n      >\n        <Text style={styles.startText}>▶ START GAME</Text>\n      </TouchableOpacity>\n\n      <Text style={styles.footer}>Powered by react-native-game-engine</Text>\n    </View>\n  );\n}\n\nconst styles = StyleSheet.create({\n  container: { flex: 1, backgroundColor: '#000', alignItems: 'center', justifyContent: 'center' },\n  emoji: { fontSize: 60, marginBottom: 10 },\n  title: { fontSize: 36, fontWeight: 'bold', color: '#0f0', letterSpacing: 3 },\n  subtitle: { fontSize: 16, color: '#0a0', marginBottom: 20 },\n  highScore: { fontSize: 18, color: '#fff', marginBottom: 40 },\n  startButton: { borderWidth: 2, borderColor: '#0f0', paddingHorizontal: 40, paddingVertical: 15, borderRadius: 4 },\n  startText: { fontSize: 22, fontWeight: 'bold', color: '#0f0' },\n  footer: { position: 'absolute', bottom: 40, color: '#444', fontSize: 11 },\n});", 'filename' => 'screens/HomeScreen.tsx'],
                    ['type' => 'tip', 'text' => 'ホーム画面は通常の React Native コンポーネントです。GameEngine はゲーム画面でのみ使います。Inertia.js アプリでも全ページで Inertia を使うわけではなく、必要なページだけで使うのと同じ考え方です。'],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'ゲームエンジン (GameEngine) を使うのはどの画面？', 'options' => ['ゲーム画面のみ', 'すべての画面', 'ホーム画面のみ', 'ナビゲーション全体'], 'correct' => 0, 'explanation' => 'GameEngine はゲームロジックが必要なゲーム画面でのみ使い、ホーム画面などは通常の React Native コンポーネントで作ります。'],
                    ]],
                ],
            ],
            [
                'number' => 5,
                'title' => '自機エンティティ',
                'summary' => 'プレイヤーエンティティの作成とレンダリング、型定義を行います。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'TypeScript で型安全なエンティティ定義'],
                    ['type' => 'text', 'text' => 'TypeScript を使ってエンティティの型を定義し、安全にゲームオブジェクトを管理します。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "// types/index.ts\nexport interface Position {\n  x: number;\n  y: number;\n}\n\nexport interface Size {\n  width: number;\n  height: number;\n}\n\nexport interface PlayerEntity {\n  position: Position;\n  size: Size;\n  speed: number;\n  renderer: React.ReactElement;\n}\n\nexport interface BulletEntity {\n  position: Position;\n  size: Size;\n  speed: number;\n  active: boolean;\n  renderer: React.ReactElement;\n}\n\nexport interface EnemyEntity {\n  position: Position;\n  size: Size;\n  type: number;\n  alive: boolean;\n  renderer: React.ReactElement;\n}\n\nexport interface GameEntities {\n  player: PlayerEntity;\n  [key: string]: any; // 動的に追加される敵や弾\n}", 'filename' => 'types/index.ts'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'プレイヤーレンダラーの作成'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { View, StyleSheet } from 'react-native';\nimport type { Position, Size } from '../types';\n\ninterface Props {\n  position: Position;\n  size: Size;\n}\n\nexport default function PlayerRenderer({ position, size }: Props) {\n  return (\n    <View style={[\n      styles.player,\n      {\n        left: position.x,\n        top: position.y,\n        width: size.width,\n        height: size.height,\n      },\n    ]}>\n      {/* 自機のデザイン：三角形風 */}\n      <View style={styles.cannon} />\n      <View style={styles.body} />\n    </View>\n  );\n}\n\nconst styles = StyleSheet.create({\n  player: { position: 'absolute', alignItems: 'center' },\n  cannon: {\n    width: 4,\n    height: 12,\n    backgroundColor: '#0f0',\n    marginBottom: -2,\n  },\n  body: {\n    width: '100%',\n    height: '70%',\n    backgroundColor: '#0f0',\n    borderTopLeftRadius: 8,\n    borderTopRightRadius: 8,\n    borderBottomLeftRadius: 2,\n    borderBottomRightRadius: 2,\n  },\n});", 'filename' => 'renderers/PlayerRenderer.tsx'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'エンティティの初期化'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { Dimensions } from 'react-native';\nimport PlayerRenderer from '../renderers/PlayerRenderer';\nimport type { GameEntities } from '../types';\n\nconst { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');\n\nexport function createEntities(): GameEntities {\n  const playerSize = { width: 40, height: 40 };\n  return {\n    player: {\n      position: {\n        x: SCREEN_WIDTH / 2 - playerSize.width / 2,\n        y: SCREEN_HEIGHT - 120,\n      },\n      size: playerSize,\n      speed: 5,\n      renderer: <PlayerRenderer />,\n    },\n  };\n}", 'filename' => 'entities/index.tsx'],
                    ['type' => 'text', 'text' => 'renderer に渡した <PlayerRenderer /> には、GameEngine がエンティティの全プロパティ（position, size など）を自動的に props として注入します。手動で props を渡す必要はありません。'],
                    ['type' => 'tip', 'text' => 'Laravel の Eloquent で $appends を定義してアクセサを自動的にJSONに含めるように、GameEngine はエンティティのプロパティをレンダラーに自動注入します。'],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'エンティティの renderer に渡したコンポーネントに props はどう渡される？', 'options' => ['GameEngine が自動で注入する', '手動で props を渡す必要がある', 'Context API で共有する', 'グローバル変数でアクセスする'], 'correct' => 0, 'explanation' => 'GameEngine はエンティティの全プロパティ（position, size等）を自動的に renderer の props として注入します。'],
                    ]],
                ],
            ],
            [
                'number' => 6,
                'title' => '入力システム',
                'summary' => 'タッチイベントを処理するSystemを実装し、自機を操作できるようにします。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'タッチイベントの処理'],
                    ['type' => 'text', 'text' => 'GameEngine は touches 配列を通じてタッチイベントを System に渡します。これを使って自機の移動と弾の発射を実装します。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { Dimensions } from 'react-native';\n\nconst SCREEN_WIDTH = Dimensions.get('window').width;\n\n// 自機移動 System\nexport const MovePlayerSystem = (\n  entities: any,\n  { touches }: any\n) => {\n  const player = entities.player;\n\n  touches\n    .filter((t: any) => t.type === 'move')\n    .forEach((t: any) => {\n      // タッチ位置に自機を追従\n      let newX = t.event.pageX - player.size.width / 2;\n      // 画面端の制限\n      newX = Math.max(0, Math.min(newX, SCREEN_WIDTH - player.size.width));\n      player.position.x = newX;\n    });\n\n  return entities;\n};", 'filename' => 'systems/MovePlayerSystem.ts'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'タッチイベントの種類'],
                    ['type' => 'list', 'items' => ['start: 指が画面に触れた瞬間', 'move: 指が画面上を移動中', 'end: 指が画面から離れた瞬間', 'press: 短いタップ（タッチして離す）']],
                    ['type' => 'heading', 'level' => 3, 'text' => '弾の発射 System'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import BulletRenderer from '../renderers/BulletRenderer';\n\nlet bulletCount = 0;\nconst FIRE_INTERVAL = 300; // 発射間隔(ms)\nlet lastFireTime = 0;\n\nexport const FireSystem = (\n  entities: any,\n  { touches, time }: any\n) => {\n  // タップで発射（連射制限あり）\n  const now = time.current;\n  const taps = touches.filter((t: any) => t.type === 'press');\n\n  if (taps.length > 0 && now - lastFireTime > FIRE_INTERVAL) {\n    lastFireTime = now;\n    const player = entities.player;\n    const bulletId = `bullet_\${bulletCount++}`;\n\n    entities[bulletId] = {\n      position: {\n        x: player.position.x + player.size.width / 2 - 2,\n        y: player.position.y - 15,\n      },\n      size: { width: 4, height: 12 },\n      speed: 8,\n      active: true,\n      renderer: <BulletRenderer />,\n    };\n  }\n\n  return entities;\n};", 'filename' => 'systems/FireSystem.tsx'],
                    ['type' => 'text', 'text' => 'ECS パターンでは System が新しいエンティティを entities オブジェクトに追加することで、動的にゲームオブジェクトを生成できます。弾のように大量に生成・削除されるオブジェクトの管理に適しています。'],
                    ['type' => 'comparison', 'title' => '動的オブジェクト生成の比較', 'react' => "// コースA: useState で配列管理\nconst [bullets, setBullets] = useState([]);\n\nconst fire = () => {\n  setBullets(prev => [...prev, {\n    id: nextId++,\n    x: playerX,\n    y: playerY,\n  }]);\n};", 'reactNative' => "// コースB: entities に追加\nconst FireSystem = (entities, args) => {\n  entities[`bullet_\${id++}`] = {\n    position: { x, y },\n    speed: 8,\n    renderer: <BulletRenderer />,\n  };\n  return entities;\n};"],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'GameEngine が System に渡すタッチイベントの配列名は？', 'options' => ['touches', 'events', 'gestures', 'inputs'], 'correct' => 0, 'explanation' => 'System の第2引数の touches 配列にタッチイベントが格納されます。'],
                        ['question' => 'ECS で新しいゲームオブジェクト（弾など）を動的に追加する方法は？', 'options' => ['entities オブジェクトに新しいキーで追加', 'setState で配列に追加', 'GameEngine の API を呼ぶ', 'コンストラクタで new する'], 'correct' => 0, 'explanation' => 'System 内で entities[newKey] = {...} として追加し、return entities すれば新しいエンティティが描画されます。'],
                    ]],
                ],
            ],
            [
                'number' => 7,
                'title' => '弾の発射システム',
                'summary' => '弾エンティティの動的生成と移動Systemを実装します。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => '弾の移動 System'],
                    ['type' => 'text', 'text' => '弾は毎フレーム上方向に移動します。画面外に出た弾はエンティティから削除してメモリを節約します。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "export const MoveBulletsSystem = (entities: any, { time }: any) => {\n  const bulletKeys = Object.keys(entities).filter(key => key.startsWith('bullet_'));\n\n  bulletKeys.forEach(key => {\n    const bullet = entities[key];\n    if (!bullet.active) return;\n\n    // 上方向に移動（delta で速度補正）\n    bullet.position.y -= bullet.speed * (time.delta / 16);\n\n    // 画面外に出たら削除\n    if (bullet.position.y < -20) {\n      delete entities[key];\n    }\n  });\n\n  return entities;\n};", 'filename' => 'systems/MoveBulletsSystem.ts'],
                    ['type' => 'heading', 'level' => 3, 'text' => '弾のレンダラー'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { View, StyleSheet } from 'react-native';\n\nexport default function BulletRenderer({ position, size }: any) {\n  return (\n    <View\n      style={[\n        styles.bullet,\n        {\n          left: position.x,\n          top: position.y,\n          width: size.width,\n          height: size.height,\n        },\n      ]}\n    />\n  );\n}\n\nconst styles = StyleSheet.create({\n  bullet: {\n    position: 'absolute',\n    backgroundColor: '#ff0',\n    borderRadius: 2,\n  },\n});", 'filename' => 'renderers/BulletRenderer.tsx'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'GameEngine に System を登録'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { GameEngine } from 'react-native-game-engine';\nimport { createEntities } from '../entities';\nimport { MovePlayerSystem } from '../systems/MovePlayerSystem';\nimport { FireSystem } from '../systems/FireSystem';\nimport { MoveBulletsSystem } from '../systems/MoveBulletsSystem';\n\nexport default function GameScreen() {\n  return (\n    <GameEngine\n      style={{ flex: 1, backgroundColor: '#000' }}\n      entities={createEntities()}\n      systems={[\n        MovePlayerSystem,   // 1. 自機の移動\n        FireSystem,          // 2. 弾の発射\n        MoveBulletsSystem,   // 3. 弾の移動\n      ]}\n    />\n  );\n}", 'filename' => 'screens/GameScreen.tsx'],
                    ['type' => 'text', 'text' => 'systems 配列に登録した順序で System が毎フレーム実行されます。順序が重要な場合があります（例：移動→衝突判定→描画）。'],
                    ['type' => 'tip', 'text' => 'Laravel のミドルウェアパイプラインと同様に、systems は配列の順序で実行されます。「入力処理→移動→衝突判定→クリーンアップ」の順で並べるのが一般的です。'],
                    ['type' => 'warning', 'text' => 'delete entities[key] でエンティティを削除すると、対応するレンダラーも自動的に画面から消えます。ただし、大量に delete を繰り返すとパフォーマンスに影響する場合があります。'],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'systems 配列の実行順序は？', 'options' => ['配列のインデックス順（先頭から）', 'ランダム', '並列実行', '逆順'], 'correct' => 0, 'explanation' => 'systems は配列の先頭から順に毎フレーム実行されます。Laravel のミドルウェアと同様に順序が重要です。'],
                        ['question' => '画面外に出た弾エンティティを削除する方法は？', 'options' => ['delete entities[key]', 'entities[key] = null', 'entities.remove(key)', 'entities[key].destroy()'], 'correct' => 0, 'explanation' => 'JavaScript の delete 演算子でエンティティを削除すると、GameEngine が自動的にレンダリングから除外します。'],
                    ]],
                ],
            ],
            [
                'number' => 8,
                'title' => '敵エンティティと移動',
                'summary' => '敵の一括管理と移動パターンSystemを実装します。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => '敵エンティティの一括生成'],
                    ['type' => 'text', 'text' => '5行×8列の敵をエンティティとして一括生成します。各敵には一意のキー名を付けて管理します。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { Dimensions } from 'react-native';\nimport EnemyRenderer from '../renderers/EnemyRenderer';\n\nconst SCREEN_WIDTH = Dimensions.get('window').width;\nconst ENEMY_ROWS = 5;\nconst ENEMY_COLS = 8;\nconst ENEMY_SIZE = 30;\nconst ENEMY_GAP = 10;\n\nexport function createEnemyEntities(): Record<string, any> {\n  const entities: Record<string, any> = {};\n  const startX = (SCREEN_WIDTH - ENEMY_COLS * (ENEMY_SIZE + ENEMY_GAP)) / 2;\n\n  for (let row = 0; row < ENEMY_ROWS; row++) {\n    for (let col = 0; col < ENEMY_COLS; col++) {\n      const key = `enemy_\${row}_\${col}`;\n      entities[key] = {\n        position: {\n          x: startX + col * (ENEMY_SIZE + ENEMY_GAP),\n          y: 80 + row * (ENEMY_SIZE + ENEMY_GAP),\n        },\n        size: { width: ENEMY_SIZE, height: ENEMY_SIZE },\n        type: Math.min(row, 2),\n        alive: true,\n        renderer: <EnemyRenderer />,\n      };\n    }\n  }\n\n  return entities;\n}\n\n// createEntities に統合\nexport function createEntities() {\n  return {\n    player: { /* ... */ },\n    ...createEnemyEntities(),\n    // ゲーム全体の状態を管理するメタエンティティ\n    gameState: {\n      direction: 1,  // 1: 右, -1: 左\n      speed: 1,\n      renderer: null, // 描画なし\n    },\n  };\n}", 'filename' => 'entities/index.tsx'],
                    ['type' => 'heading', 'level' => 3, 'text' => '敵レンダラー'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { View, Text, StyleSheet } from 'react-native';\n\nconst ENEMY_DESIGNS = ['👾', '🛸', '👽'];\n\nexport default function EnemyRenderer({ position, size, type, alive }: any) {\n  if (!alive) return null;\n\n  return (\n    <View style={[\n      styles.container,\n      { left: position.x, top: position.y, width: size.width, height: size.height },\n    ]}>\n      <Text style={styles.emoji}>{ENEMY_DESIGNS[type] || '👾'}</Text>\n    </View>\n  );\n}\n\nconst styles = StyleSheet.create({\n  container: { position: 'absolute', alignItems: 'center', justifyContent: 'center' },\n  emoji: { fontSize: 24 },\n});", 'filename' => 'renderers/EnemyRenderer.tsx'],
                    ['type' => 'heading', 'level' => 3, 'text' => '敵の一斉移動 System'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { Dimensions } from 'react-native';\n\nconst SCREEN_WIDTH = Dimensions.get('window').width;\nconst ENEMY_SPEED = 1.5;\nconst DROP_DISTANCE = 20;\n\nexport const MoveEnemiesSystem = (entities: any, { time }: any) => {\n  const gameState = entities.gameState;\n  const enemyKeys = Object.keys(entities).filter(k => k.startsWith('enemy_'));\n  const aliveEnemies = enemyKeys.filter(k => entities[k].alive);\n\n  if (aliveEnemies.length === 0) return entities;\n\n  // 端に到達したか確認\n  let hitEdge = false;\n  aliveEnemies.forEach(key => {\n    const enemy = entities[key];\n    if (enemy.position.x + enemy.size.width >= SCREEN_WIDTH - 10 && gameState.direction > 0) {\n      hitEdge = true;\n    }\n    if (enemy.position.x <= 10 && gameState.direction < 0) {\n      hitEdge = true;\n    }\n  });\n\n  // 端に到達したら方向反転＋1段下降\n  if (hitEdge) {\n    gameState.direction *= -1;\n    aliveEnemies.forEach(key => {\n      entities[key].position.y += DROP_DISTANCE;\n    });\n    // 速度を少し上げる（難易度上昇）\n    gameState.speed = Math.min(gameState.speed + 0.1, 4);\n  }\n\n  // 全敵を移動\n  const moveAmount = ENEMY_SPEED * gameState.speed * gameState.direction * (time.delta / 16);\n  aliveEnemies.forEach(key => {\n    entities[key].position.x += moveAmount;\n  });\n\n  return entities;\n};", 'filename' => 'systems/MoveEnemiesSystem.ts'],
                    ['type' => 'text', 'text' => 'gameState エンティティを使ってゲーム全体の状態（方向、速度）を管理します。renderer: null にすれば描画されないため、メタデータの管理に使えます。'],
                    ['type' => 'tip', 'text' => 'gameState のような「描画しないエンティティ」はゲーム全体の状態管理に便利です。Laravel のシングルトンサービスに似た役割で、複数の System 間で状態を共有できます。'],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'renderer: null のエンティティの役割は？', 'options' => ['描画なしでゲーム状態のメタデータを管理する', '非表示の敵を管理する', 'エラーを防ぐダミー', 'パフォーマンス最適化'], 'correct' => 0, 'explanation' => 'renderer: null のエンティティは画面に描画されず、ゲーム全体の状態（方向、速度など）を複数の System 間で共有するために使います。'],
                        ['question' => '敵の移動速度を徐々に上げる（難易度上昇）にはどうする？', 'options' => ['gameState.speed を段階的に増加させる', '新しい System を追加する', '敵エンティティを毎フレーム再作成する', 'setInterval の間隔を変える'], 'correct' => 0, 'explanation' => 'gameState エンティティの speed 値を段階的に上げることで、同じ System のまま難易度を動的に変更できます。'],
                    ]],
                ],
            ],
            [
                'number' => 9,
                'title' => '衝突判定システム',
                'summary' => 'Collision Detection Systemを実装し、弾と敵の当たり判定を処理します。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => '衝突判定 System の実装'],
                    ['type' => 'text', 'text' => 'ECS パターンでは衝突判定も独立した System として実装します。ここでは AABB（Axis-Aligned Bounding Box）という矩形同士の重なりを判定するシンプルな方法を使います。弾と敵の衝突、敵と自機の接近をチェックします。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "// utils/collision.ts\nexport interface Rect {\n  x: number;\n  y: number;\n  width: number;\n  height: number;\n}\n\nexport function isColliding(a: Rect, b: Rect): boolean {\n  return (\n    a.x < b.x + b.width &&\n    a.x + a.width > b.x &&\n    a.y < b.y + b.height &&\n    a.y + a.height > b.y\n  );\n}\n\nexport function entityToRect(entity: any): Rect {\n  return {\n    x: entity.position.x,\n    y: entity.position.y,\n    width: entity.size.width,\n    height: entity.size.height,\n  };\n}", 'filename' => 'utils/collision.ts'],
                    ['type' => 'heading', 'level' => 3, 'text' => '衝突判定 System'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { isColliding, entityToRect } from '../utils/collision';\nimport { Dimensions } from 'react-native';\n\nconst SCREEN_HEIGHT = Dimensions.get('window').height;\n\nexport const CollisionSystem = (\n  entities: any,\n  { dispatch }: any\n) => {\n  const bulletKeys = Object.keys(entities).filter(k => k.startsWith('bullet_'));\n  const enemyKeys = Object.keys(entities).filter(k => k.startsWith('enemy_'));\n\n  // 弾 vs 敵の衝突判定\n  bulletKeys.forEach(bulletKey => {\n    const bullet = entities[bulletKey];\n    if (!bullet) return;\n\n    for (const enemyKey of enemyKeys) {\n      const enemy = entities[enemyKey];\n      if (!enemy || !enemy.alive) continue;\n\n      if (isColliding(entityToRect(bullet), entityToRect(enemy))) {\n        // 敵を倒す\n        enemy.alive = false;\n        // 弾を削除\n        delete entities[bulletKey];\n        // スコア加算イベント\n        const points = (3 - enemy.type) * 10;\n        dispatch({ type: 'score', points });\n        break; // 1つの弾で1体の敵のみ倒す\n      }\n    }\n  });\n\n  // 敵が画面下端に到達したらゲームオーバー\n  const aliveEnemies = enemyKeys.filter(k => entities[k]?.alive);\n  const reachedBottom = aliveEnemies.some(\n    k => entities[k].position.y + entities[k].size.height >= SCREEN_HEIGHT - 120\n  );\n\n  if (reachedBottom) {\n    dispatch({ type: 'game-over' });\n  }\n\n  // 全敵撃破チェック\n  if (aliveEnemies.length === 0 && enemyKeys.length > 0) {\n    dispatch({ type: 'game-clear' });\n  }\n\n  return entities;\n};", 'filename' => 'systems/CollisionSystem.ts'],
                    ['type' => 'text', 'text' => '衝突判定 System は他の System（移動など）の後に実行されるよう、systems 配列の後方に配置します。Laravel のミドルウェアの実行順序と同じように、処理の依存関係を考慮して順序を決めます。'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'System の実行順序'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "systems={[\n  MovePlayerSystem,    // 1. 自機移動\n  FireSystem,           // 2. 弾の発射\n  MoveBulletsSystem,    // 3. 弾の移動\n  MoveEnemiesSystem,    // 4. 敵の移動\n  CollisionSystem,      // 5. 衝突判定（移動後に実行）\n]}"],
                    ['type' => 'tip', 'text' => 'System の実行順序は「入力 → 移動 → 衝突判定 → 結果処理」が定番です。Laravel のリクエストライフサイクル（ミドルウェア → コントローラー → レスポンス）に対応する概念です。'],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => '衝突判定 System はいつ実行すべき？', 'options' => ['移動 System の後', '移動 System の前', '最初に実行', '順序は関係ない'], 'correct' => 0, 'explanation' => '衝突判定は全オブジェクトの移動が完了した後に実行することで、正確な判定ができます。'],
                        ['question' => '衝突判定で使用した AABB は何の略？', 'options' => ['Axis-Aligned Bounding Box', 'Advanced Automatic Boundary Builder', 'Absolute Area Bounding Box', 'Aligned Axis Base Box'], 'correct' => 0, 'explanation' => 'AABB = Axis-Aligned Bounding Box（軸に沿った境界ボックス）。矩形同士の重なりを4条件で判定する最もシンプルな衝突判定です。'],
                    ]],
                ],
            ],
            [
                'number' => 10,
                'title' => 'ゲーム状態管理',
                'summary' => 'スコア、ライフ、ゲームオーバー処理とイベントディスパッチを統合します。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'GameEngine のイベント処理で状態管理'],
                    ['type' => 'text', 'text' => 'System から dispatch したイベントを GameEngine の onEvent で受け取り、React の state で UI を更新します。ゲームロジック（System）と UI 表示（React）を綺麗に分離できます。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { useState, useRef, useCallback } from 'react';\nimport { View, Text, TouchableOpacity, StyleSheet, Dimensions } from 'react-native';\nimport { GameEngine } from 'react-native-game-engine';\nimport AsyncStorage from '@react-native-async-storage/async-storage';\nimport { createEntities } from '../entities';\nimport { MovePlayerSystem } from '../systems/MovePlayerSystem';\nimport { FireSystem } from '../systems/FireSystem';\nimport { MoveBulletsSystem } from '../systems/MoveBulletsSystem';\nimport { MoveEnemiesSystem } from '../systems/MoveEnemiesSystem';\nimport { CollisionSystem } from '../systems/CollisionSystem';\n\nexport default function GameScreen({ navigation }: any) {\n  const engineRef = useRef<any>(null);\n  const [score, setScore] = useState(0);\n  const [lives, setLives] = useState(3);\n  const [gameOver, setGameOver] = useState(false);\n  const [gameClear, setGameClear] = useState(false);\n  const [running, setRunning] = useState(true);\n\n  const saveHighScore = async (finalScore: number) => {\n    const current = await AsyncStorage.getItem('highScore');\n    if (!current || finalScore > parseInt(current)) {\n      await AsyncStorage.setItem('highScore', finalScore.toString());\n    }\n  };\n\n  const handleEvent = useCallback(async (event: any) => {\n    switch (event.type) {\n      case 'score':\n        setScore(prev => prev + event.points);\n        break;\n      case 'player-hit':\n        setLives(prev => {\n          const newLives = prev - 1;\n          if (newLives <= 0) {\n            setGameOver(true);\n            setRunning(false);\n          }\n          return newLives;\n        });\n        break;\n      case 'game-over':\n        setGameOver(true);\n        setRunning(false);\n        saveHighScore(score);\n        break;\n      case 'game-clear':\n        setGameClear(true);\n        setRunning(false);\n        saveHighScore(score);\n        break;\n    }\n  }, [score]);\n\n  const restart = () => {\n    setScore(0);\n    setLives(3);\n    setGameOver(false);\n    setGameClear(false);\n    setRunning(true);\n    engineRef.current?.swap(createEntities());\n  };\n\n  return (\n    <View style={styles.container}>\n      {/* ヘッダー */}\n      <View style={styles.header}>\n        <Text style={styles.headerText}>SCORE: {score}</Text>\n        <Text style={styles.headerText}>{'♥'.repeat(lives)}</Text>\n      </View>\n\n      {/* ゲーム画面 */}\n      <GameEngine\n        ref={engineRef}\n        style={styles.game}\n        entities={createEntities()}\n        systems={[\n          MovePlayerSystem,\n          FireSystem,\n          MoveBulletsSystem,\n          MoveEnemiesSystem,\n          CollisionSystem,\n        ]}\n        running={running}\n        onEvent={handleEvent}\n      />\n\n      {/* ゲームオーバー/クリア モーダル */}\n      {(gameOver || gameClear) && (\n        <View style={styles.overlay}>\n          <Text style={styles.overlayTitle}>\n            {gameClear ? 'STAGE CLEAR!' : 'GAME OVER'}\n          </Text>\n          <Text style={styles.overlayScore}>SCORE: {score}</Text>\n          <TouchableOpacity style={styles.button} onPress={restart}>\n            <Text style={styles.buttonText}>RETRY</Text>\n          </TouchableOpacity>\n          <TouchableOpacity onPress={() => navigation.navigate('Home')}>\n            <Text style={styles.homeLink}>HOME</Text>\n          </TouchableOpacity>\n        </View>\n      )}\n    </View>\n  );\n}\n\nconst styles = StyleSheet.create({\n  container: { flex: 1, backgroundColor: '#000' },\n  header: { flexDirection: 'row', justifyContent: 'space-between', padding: 10, paddingTop: 50 },\n  headerText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },\n  game: { flex: 1 },\n  overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.8)', alignItems: 'center', justifyContent: 'center' },\n  overlayTitle: { fontSize: 36, fontWeight: 'bold', color: '#0f0', marginBottom: 20 },\n  overlayScore: { fontSize: 24, color: '#fff', marginBottom: 30 },\n  button: { borderWidth: 2, borderColor: '#0f0', paddingHorizontal: 40, paddingVertical: 12, borderRadius: 4, marginBottom: 15 },\n  buttonText: { fontSize: 20, fontWeight: 'bold', color: '#0f0' },\n  homeLink: { fontSize: 16, color: '#888', marginTop: 10 },\n});", 'filename' => 'screens/GameScreen.tsx'],
                    ['type' => 'heading', 'level' => 3, 'text' => 'running prop でゲームの一時停止'],
                    ['type' => 'text', 'text' => 'GameEngine の running prop を false にするとゲームループが停止します。ゲームオーバー時やポーズ時に使います。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "// ゲームの一時停止/再開\n<GameEngine running={running} />\n\n// ポーズボタン\n<TouchableOpacity onPress={() => setRunning(prev => !prev)}>\n  <Text>{running ? '⏸ PAUSE' : '▶ RESUME'}</Text>\n</TouchableOpacity>"],
                    ['type' => 'heading', 'level' => 3, 'text' => 'swap でエンティティのリセット'],
                    ['type' => 'text', 'text' => 'engineRef.current.swap(newEntities) でゲーム内の全エンティティを入れ替えられます。リスタート時に初期状態のエンティティに戻すのに使います。'],
                    ['type' => 'comparison', 'title' => '状態リセットの比較', 'react' => "// コースA: 個別に state をリセット\nfunction restart() {\n  setScore(0);\n  setLives(3);\n  setEnemies(createEnemies());\n  setBullets([]);\n  setGameOver(false);\n}", 'reactNative' => "// コースB: swap で一括リセット\nfunction restart() {\n  setScore(0);\n  setLives(3);\n  setGameOver(false);\n  engineRef.current?.swap(createEntities());\n}"],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'GameEngine のゲームループを停止するには？', 'options' => ['running prop を false にする', 'engineRef.current.stop() を呼ぶ', 'systems を空配列にする', 'entities を null にする'], 'correct' => 0, 'explanation' => 'running={false} でゲームループが停止します。true に戻すと再開します。'],
                        ['question' => 'ゲームリスタート時にエンティティを初期化する方法は？', 'options' => ['engineRef.current.swap(newEntities)', 'entities を再代入する', 'GameEngine を再マウントする', 'resetEntities() を呼ぶ'], 'correct' => 0, 'explanation' => 'swap メソッドで全エンティティを新しいオブジェクトに一括入れ替えできます。'],
                    ]],
                ],
            ],
            [
                'number' => 11,
                'title' => '仕上げとデプロイ',
                'summary' => 'パフォーマンス最適化、効果音の追加、EAS Buildでのビルド手順を学びます。',
                'content' => [
                    ['type' => 'heading', 'level' => 2, 'text' => 'パフォーマンス最適化'],
                    ['type' => 'text', 'text' => 'ECS パターンの最大の利点の一つは、System を個別に最適化できることです。重い処理を特定の System に集約し、実行頻度を調整できます。'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { CollisionSystem } from './CollisionSystem';\n\n// フレームスキップで負荷軽減\nlet frameCount = 0;\n\nexport const OptimizedCollisionSystem = (entities: any, args: any) => {\n  frameCount++;\n  // 衝突判定は2フレームに1回実行（負荷軽減）\n  if (frameCount % 2 !== 0) return entities;\n\n  return CollisionSystem(entities, args);\n};"],
                    ['type' => 'warning', 'text' => 'react-native-game-engine ではエンティティのプロパティを直接書き換え（ミューテーション）するため、React.memo をレンダラーに使うと props の参照が変わらず再描画がスキップされ、表示が更新されなくなります。ECS パターンでは memo 化は避けてください。'],
                    ['type' => 'heading', 'level' => 3, 'text' => '効果音の追加'],
                    ['type' => 'code', 'language' => 'bash', 'code' => 'npx expo install expo-av'],
                    ['type' => 'code', 'language' => 'tsx', 'code' => "import { Audio } from 'expo-av';\n\n// サウンドマネージャー\nclass SoundManager {\n  private sounds: Map<string, Audio.Sound> = new Map();\n\n  async preload() {\n    const soundFiles: Record<string, any> = {\n      shoot: require('../assets/sounds/shoot.mp3'),\n      explosion: require('../assets/sounds/explosion.mp3'),\n      gameOver: require('../assets/sounds/gameover.mp3'),\n    };\n\n    for (const [key, file] of Object.entries(soundFiles)) {\n      const { sound } = await Audio.Sound.createAsync(file);\n      this.sounds.set(key, sound);\n    }\n  }\n\n  async play(name: string) {\n    const sound = this.sounds.get(name);\n    if (sound) {\n      await sound.replayAsync();\n    }\n  }\n\n  async unloadAll() {\n    for (const sound of this.sounds.values()) {\n      await sound.unloadAsync();\n    }\n    this.sounds.clear();\n  }\n}\n\nexport const soundManager = new SoundManager();", 'filename' => 'utils/SoundManager.ts'],
                    ['type' => 'heading', 'level' => 2, 'text' => 'EAS Build でビルド'],
                    ['type' => 'code', 'language' => 'bash', 'code' => "# EAS CLI インストール\nnpm install -g eas-cli\n\n# ログイン\neas login\n\n# ビルド設定の初期化\neas build:configure\n\n# 開発ビルド（実機テスト用）\neas build --profile development --platform ios\neas build --profile development --platform android\n\n# 本番ビルド（ストア提出用）\neas build --profile production --platform ios\neas build --profile production --platform android\n\n# OTA アップデート（コードのみの更新）\neas update --branch production"],
                    ['type' => 'heading', 'level' => 3, 'text' => 'eas.json の設定'],
                    ['type' => 'code', 'language' => 'json', 'code' => "{\n  \"cli\": { \"version\": \">= 5.0.0\" },\n  \"build\": {\n    \"development\": {\n      \"developmentClient\": true,\n      \"distribution\": \"internal\"\n    },\n    \"preview\": {\n      \"distribution\": \"internal\"\n    },\n    \"production\": {\n      \"autoIncrement\": true\n    }\n  }\n}", 'filename' => 'eas.json'],
                    ['type' => 'tip', 'text' => 'EAS Build のプロファイル（development, preview, production）は Laravel の .env 環境（local, staging, production）に対応する概念です。環境ごとに異なる設定でビルドできます。'],
                    ['type' => 'warning', 'text' => 'iOS ビルドには Apple Developer Program ($99/年)、Android ストア公開には Google Play Developer ($25/一回) の登録が必要です。'],
                    ['type' => 'heading', 'level' => 2, 'text' => 'コース完了！🎮'],
                    ['type' => 'text', 'text' => 'おめでとうございます！react-native-game-engine を使った ECS パターンでのインベーダーゲーム開発を完了しました。ECS パターンは複雑なゲームロジックを構造的に管理できる強力な設計パターンです。コースAのコンポーネント方式と比較して、以下の違いを実感できたはずです。'],
                    ['type' => 'list', 'items' => ['ゲームループの自動管理 → setInterval 不要', 'System による処理の分離 → 保守性の向上', 'Entity の動的追加/削除 → 柔軟なオブジェクト管理', 'dispatch によるイベント駆動 → ロジックとUIの分離']],
                    ['type' => 'text', 'text' => '次のステップとして、敵の弾の追加、ボス戦の実装、ステージ制の導入など、ゲームをさらに拡張してみてください！'],
                    ['type' => 'quiz', 'questions' => [
                        ['question' => 'EAS Build で本番用ビルドを作成するコマンドは？', 'options' => ['eas build --profile production', 'expo build:production', 'npm run build:production', 'eas deploy --production'], 'correct' => 0, 'explanation' => 'eas build --profile production --platform ios/android で本番用ビルドを作成します。'],
                        ['question' => 'ECS パターンの最大の利点は？', 'options' => ['処理の分離による保守性とスケーラビリティ', '処理速度が100倍になる', 'コード量が半分になる', '3Dグラフィックが使える'], 'correct' => 0, 'explanation' => 'ECS パターンは Entity/Component/System の分離により、複雑なゲームロジックを構造的に管理でき、保守性とスケーラビリティに優れています。'],
                    ]],
                ],
            ],
        ];
    }
}
